# Site settings
title: Go Automated!
header-img: img/home-bg.jpg
email: eric.s.bullington@gmail.com
description: "Easy Small Business Automation and Productivity"
baseurl: "/goautomated"
url: "http://esbullington.github.io/goautomated"
twitter_username: eric_bullington
github_username:  esbullington

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
